# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Math-BigInt
version:      1.73
version_from: lib/Math/BigInt.pm
installdirs:  perl
requires:
    Scalar::Util:                  1.13

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
