---
abstract: 'Arbitrary size integer/float math package'
author:
  - 'Original code by Mark Biggar, overloaded interface by Ilya Zakharevich.'
  - 'Tels <nospam-abuse@bloodgate.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.62
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Math-BigInt
no_index:
  directory:
    - examples
    - inc
    - t
recommends:
  Math::BigInt::FastCalc: 0.24
  Math::BigInt::GMP: 1.24
  Math::BigInt::Pari: 1.13
  Math::BigRat: 0.22
  bignum: 0.22
requires:
  perl: 5.006002
resources:
  license: http://dev.perl.org/licenses/
version: 1.98
