--- #YAML:1.0
name: Math-BigInt
version: 1.74
version_from: lib/Math/BigInt.pm
license: perl
distribution_type: module
generated_by: Math-BigInt version 1.74
installdirs: perl
requires:
  Scalar::Util: 1.13
