--- 
abstract: Arbitrary size integer/float math package
author: Tels <nospam-abuse@bloodgate.com>
build_requires: 
  Test::More: 0.62
distribution_type: module
generated_by: Module::Install version 0.65
installdirs: perl
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Math-BigInt
no_index: 
  directory: 
    - examples
    - inc
    - t
recommends: 
  Math::BigInt::FastCalc: 0.14
  Math::BigInt::GMP: 1.21
  Math::BigInt::Pari: 1.12
  Math::BigRat: 0.19
  bignum: 0.21
requires: 
  perl: 5.6.2
version: 1.85
