---
abstract: 'Arbitrary size integer/float math package'
author:
  - '=over 4, Peter John Acklam <pjacklam@online.no>'
build_requires:
  ExtUtils::MakeMaker: '6.59'
  Test::More: '0.9301'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.1, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Math-BigInt
no_index:
  directory:
    - t
    - inc
requires:
  Math::Complex: '1.39'
  Test::More: '0.9301'
  perl: '5.006002'
version: '1.999710'
x_serialization_backend: 'CPAN::Meta::YAML version 0.016'
